name: Code Coverage
on:
  push:
    branches:
    - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Check all
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-features
  cover:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: nimbustech/postgres-ssl:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        volumes:
          - tests/cert:/var/ssl
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Load test data
        run: psql -h localhost -U postgres -d postgres < tests/load-data.sql
        env:
          PGPASSWORD: "postgres"
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.11.0'
          args: --out Xml --all --all-features
        env:
          TEST_URL: "postgresql://localhost/postgres?user=postgres&password=postgres"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
